#!/usr/bin/env node

/**
 * build-workers.js - Compile TypeScript workers to JavaScript
 *
 * This script compiles all TypeScript workers from src/workers/ to public/workers/
 * using esbuild for fast, reliable compilation.
 *
 * Usage: npm run build:workers
 */

import { readdirSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, "..");

const WORKERS_SRC_DIR = join(projectRoot, "src/workers");
const WORKERS_PUBLIC_DIR = join(projectRoot, "public/workers");

/**
 * Get all TypeScript worker files
 */
function getWorkerFiles() {
  if (!existsSync(WORKERS_SRC_DIR)) {
    console.warn("[build-workers] No src/workers directory found");
    return [];
  }

  const files = readdirSync(WORKERS_SRC_DIR);
  return files.filter((file) => file.endsWith(".worker.ts"));
}

/**
 * Compile a TypeScript worker file using esbuild
 */
async function compileWorker(workerFile) {
  const srcPath = join(WORKERS_SRC_DIR, workerFile);
  const outputName = workerFile.replace(".ts", ".js");
  const outputPath = join(WORKERS_PUBLIC_DIR, outputName);

  console.log(`[build-workers] Compiling ${workerFile}...`);

  try {
    // Dynamic import esbuild (it's a dev dependency)
    const esbuild = await import("esbuild");

    // Determine if this worker needs bundling (e.g., stemSeparator needs onnxruntime-web)
    // Workers that use external libraries need bundling to include them
    const needsBundling =
      workerFile.includes("stemSeparator") || workerFile.includes("key");

    const buildOptions = {
      entryPoints: [srcPath],
      bundle: needsBundling, // Bundle dependencies for workers that need external libs
      outfile: outputPath,
      format: "iife", // IIFE format for classic workers
      target: "es2020",
      platform: "browser",
      sourcemap: false,
      minify: false, // Keep readable for debugging
      banner: {
        js: `/**
 * ${outputName} - ${workerFile.replace(".ts", "")} Worker (Compiled)
 *
 * Phase 9C: Compiled from src/workers/${workerFile}
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 * Edit src/workers/${workerFile} and run: npm run build:workers
 */\n`,
      },
    };

    // Note: For bundled workers, we include all dependencies
    // For non-bundled workers, they must not import external libs (or handle them at runtime)

    await esbuild.build(buildOptions);

    if (existsSync(outputPath)) {
      console.log(`[build-workers] ✅ Compiled ${workerFile} -> ${outputName}`);
      return true;
    } else {
      console.error(`[build-workers] ❌ Output not found for ${workerFile}`);
      return false;
    }
  } catch (error) {
    console.error(
      `[build-workers] ❌ Failed to compile ${workerFile}:`,
      error.message,
    );
    return false;
  }
}

/**
 * Main build function
 */
async function buildWorkers() {
  console.log("[build-workers] Building workers...\n");

  // Ensure public/workers directory exists
  if (!existsSync(WORKERS_PUBLIC_DIR)) {
    console.log(`[build-workers] Creating ${WORKERS_PUBLIC_DIR}...`);
    mkdirSync(WORKERS_PUBLIC_DIR, { recursive: true });
  }

  const workerFiles = getWorkerFiles();

  if (workerFiles.length === 0) {
    console.warn("[build-workers] No worker files found in src/workers/");
    return;
  }

  console.log(`[build-workers] Found ${workerFiles.length} worker file(s):\n`);

  let successCount = 0;
  let failCount = 0;

  for (const workerFile of workerFiles) {
    const success = await compileWorker(workerFile);
    if (success) {
      successCount++;
    } else {
      failCount++;
    }
    console.log(""); // Empty line for readability
  }

  console.log(
    `[build-workers] Summary: ${successCount} succeeded, ${failCount} failed`,
  );

  if (failCount > 0) {
    console.error("\n[build-workers] ❌ Some workers failed to compile");
    process.exit(1);
  } else {
    console.log("\n[build-workers] ✅ All workers compiled successfully");
  }
}

// Run if called directly
buildWorkers().catch((error) => {
  console.error("[build-workers] Fatal error:", error);
  process.exit(1);
});
